name: Server E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ""
      PORT: 3000
      JWT_SECRET: ${{ secrets.TESTS_JWT_SECRET }}
      JWT_ISSUER: ${{ secrets.TESTS_JWT_ISSUER }}
      BROKER_URL: ""
      QUEUE_NAME: ${{ secrets.TESTS_QUEUE_NAME }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      APP_LOGGER_PROVIDER: ${{ secrets.TESTS_APP_LOGGER_PROVIDER }}
      EVENT_EMITTER_PROVIDER: ${{ secrets.TEST_EVENT_EMITTER_PROVIDER }}
      NODE_ENV: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      
      - name: Generate Prisma client
        run: pnpm db:generate

      - name: Run tests
        id: run_tests
        run: pnpm test:e2e
        continue-on-error: true
      
      - name: Send Discord Notification
        if: always()
        env:
          JOB_STATUS: ${{ steps.run_tests.outcome }}
        run: |-
          if [ "$JOB_STATUS" = "success" ]; then
            MESSAGE="✅ All E2E tests from Techblitz Project passed!"
          else
            MESSAGE="❌ Some tests from Techblitz Project failed!"
          fi
          
          curl -X POST $DISCORD_WEBHOOK_URL \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$MESSAGE\", \"username\": \"Techblitz BOT 🤖\"}"

